### ISSUE TITLE
black backround

### ISSUE THREAD

**Issue by h808990** [kazcfz/Copy-n-Paste#12]
whenever i copy a clear image the clear part in the image is black?

**Comment by kazcfz** [comment]
It's working on my end for my use cases at least.
![image](https://github.com/user-attachments/assets/85bcaa64-8f25-430f-9f2c-a6cf8e853d89)

Which clear image were you copying from? This'll help us narrow down the exact problem

**Comment by h808990** [comment]
its ok i think its just a me problem im gusing with my firtfox or chrome not sure?
