### ISSUE TITLE
COPY From file directly

### ISSUE THREAD

**Issue by MGDFURRY** [kazcfz/Copy-n-Paste#16]
![image](https://github.com/user-attachments/assets/ca599d75-2a7b-4a98-9949-b7c4b37e0c63)

when i try to paste it just blank

![image](https://github.com/user-attachments/assets/dc7a5fb4-eb8f-48ff-b395-3b17332d32eb)

**Comment by kazcfz** [comment]
I've looked into this feature before and thought it was impossible due to Clipboard API's limitation.
Working on it now
